# Generated by Django 5.2.10 on 2026-01-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=10)),
                ('municipality', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('neighborhood', models.CharField(max_length=255)),
                ('street_type', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('external_number', models.CharField(max_length=20)),
                ('internal_number', models.CharField(blank=True, max_length=255, null=True)),
                ('cross_streets', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
