# Generated by Django 5.2.10 on 2026-01-22 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='city',
            new_name='locality',
        ),
    ]
