# Generated by Django 5.2.10 on 2026-01-21 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_remove_contact_unique_metadata_per_object_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contact',
            name='unique_contact_per_object',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='object_id',
        ),
    ]
