# Generated by Django 5.2.10 on 2026-01-15 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=12, unique=True)),
                ('legal_name', models.CharField(max_length=255)),
                ('capital_regime', models.CharField(max_length=255)),
                ('trade_name', models.CharField(max_length=255)),
                ('organization_type_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='organization_types.organizationtype')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField()),
                ('registration_location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='Active', max_length=20)),
                ('organization_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='organizations.organization')),
            ],
        ),
    ]
