# Generated by Django 5.2.10 on 2026-01-15 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='organization_type_id',
            new_name='organization_type',
        ),
        migrations.RenameField(
            model_name='organizationregistration',
            old_name='organization_id',
            new_name='organization',
        ),
    ]
