# Generated by Django 5.2.10 on 2026-01-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_rename_organization_type_id_organization_organization_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationregistration',
            name='registration_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
