# Generated by Django 5.2.10 on 2026-01-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organizationregistration_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationregistration',
            name='status',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='Activo', max_length=20),
        ),
    ]
