# Generated by Django 5.2.10 on 2026-01-21 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_remove_contact_unique_contact_per_object_and_more'),
        ('organizations', '0003_alter_organization_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='contacts.contact'),
        ),
    ]
