# Generated by Django 5.2.10 on 2026-01-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_organizationregistration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationregistration',
            name='status',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=20),
        ),
    ]
