# Generated by Django 5.2.10 on 2026-01-22 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_rename_city_address_locality'),
        ('organizations', '0004_alter_organization_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='addresses.address'),
            preserve_default=False,
        ),
    ]
