# Generated by Django 5.2.10 on 2026-01-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_organizationregistration_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationregistration',
            name='status',
        ),
        migrations.AddField(
            model_name='organizationregistration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
