# Generated by Django 5.2.10 on 2026-01-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_remove_organizationregistration_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationregistration',
            name='registration_location',
            field=models.GenericIPAddressField(),
        ),
    ]
